services:
  backend:
    build: .
    container_name: go-backend
    
    environment:
      - DB_HOST=host.docker.internal 
      - DB_PORT=1433
      - DB_USER=sa
      - DB_PASSWORD=1234
      - DB_NAME=ProductDB
    ports:
      - "8080:8080"
    restart: on-failure:5

  frontend:
    build:
      context: ./product-frontend
      args:
        - VITE_API_URL=http://localhost:8080
    container_name: vue-frontend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend
    restart: on-failure:5 